export const DATE_PICKER_VALUE_FORMAT = "YYYY/MM/DD";
export const DATE_TIME_PICKER_VALUE_FORMAT = `${DATE_PICKER_VALUE_FORMAT} HH:mm`;
export const MONTH_PICKER_VALUE_FORMAT = "YYYY年M月";
export const YEAR_PICKER_VALUE_FORMAT = "YYYY年";
