/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as actions_notifications_deliverWebPush from "../actions/notifications/deliverWebPush.js";
import type * as auth from "../auth.js";
import type * as crons from "../crons.js";
import type * as http from "../http.js";
import type * as lib_achievementReflection from "../lib/achievementReflection.js";
import type * as lib_authFields from "../lib/authFields.js";
import type * as lib_avatarStorage from "../lib/avatarStorage.js";
import type * as lib_boardScheduleColors from "../lib/boardScheduleColors.js";
import type * as lib_boardScheduleRange from "../lib/boardScheduleRange.js";
import type * as lib_catalog from "../lib/catalog.js";
import type * as lib_catalogLoader from "../lib/catalogLoader.js";
import type * as lib_categories from "../lib/categories.js";
import type * as lib_categoryFields from "../lib/categoryFields.js";
import type * as lib_completionRate from "../lib/completionRate.js";
import type * as lib_concreteAction from "../lib/concreteAction.js";
import type * as lib_concreteActionCore from "../lib/concreteActionCore.js";
import type * as lib_conditions from "../lib/conditions.js";
import type * as lib_dateArgs from "../lib/dateArgs.js";
import type * as lib_dayView from "../lib/dayView.js";
import type * as lib_domain from "../lib/domain.js";
import type * as lib_env from "../lib/env.js";
import type * as lib_errors from "../lib/errors.js";
import type * as lib_examGoal from "../lib/examGoal.js";
import type * as lib_historyBreakdown from "../lib/historyBreakdown.js";
import type * as lib_holiday from "../lib/holiday.js";
import type * as lib_holidayPreset from "../lib/holidayPreset.js";
import type * as lib_itemOrder from "../lib/itemOrder.js";
import type * as lib_itemSort from "../lib/itemSort.js";
import type * as lib_jst from "../lib/jst.js";
import type * as lib_methodOrder from "../lib/methodOrder.js";
import type * as lib_monthlyReview from "../lib/monthlyReview.js";
import type * as lib_movingAverage from "../lib/movingAverage.js";
import type * as lib_notificationCopy from "../lib/notificationCopy.js";
import type * as lib_notificationLink from "../lib/notificationLink.js";
import type * as lib_notifications from "../lib/notifications.js";
import type * as lib_owner from "../lib/owner.js";
import type * as lib_ownerFunctions from "../lib/ownerFunctions.js";
import type * as lib_preset from "../lib/preset.js";
import type * as lib_presetDigest from "../lib/presetDigest.js";
import type * as lib_rowTimer from "../lib/rowTimer.js";
import type * as lib_scheduleInstant from "../lib/scheduleInstant.js";
import type * as lib_searchText from "../lib/searchText.js";
import type * as lib_setupStatus from "../lib/setupStatus.js";
import type * as lib_share from "../lib/share.js";
import type * as lib_toeicScore from "../lib/toeicScore.js";
import type * as lib_trash from "../lib/trash.js";
import type * as lib_validators from "../lib/validators.js";
import type * as lib_volume from "../lib/volume.js";
import type * as lib_webPush from "../lib/webPush.js";
import type * as lib_weeklyReview from "../lib/weeklyReview.js";
import type * as migrations from "../migrations.js";
import type * as mutations_boardSchedule_create from "../mutations/boardSchedule/create.js";
import type * as mutations_boardSchedule_move from "../mutations/boardSchedule/move.js";
import type * as mutations_boardSchedule_remove from "../mutations/boardSchedule/remove.js";
import type * as mutations_boardSchedule_update from "../mutations/boardSchedule/update.js";
import type * as mutations_catalog_ensure from "../mutations/catalog/ensure.js";
import type * as mutations_categories_create from "../mutations/categories/create.js";
import type * as mutations_categories_remove from "../mutations/categories/remove.js";
import type * as mutations_categories_rename from "../mutations/categories/rename.js";
import type * as mutations_days_open from "../mutations/days/open.js";
import type * as mutations_days_setCondition from "../mutations/days/setCondition.js";
import type * as mutations_days_setMemo from "../mutations/days/setMemo.js";
import type * as mutations_goals_backfillCheckpointParents from "../mutations/goals/backfillCheckpointParents.js";
import type * as mutations_goals_create from "../mutations/goals/create.js";
import type * as mutations_goals_createObstacle from "../mutations/goals/createObstacle.js";
import type * as mutations_goals_recomputeMasteryProgress from "../mutations/goals/recomputeMasteryProgress.js";
import type * as mutations_goals_remove from "../mutations/goals/remove.js";
import type * as mutations_goals_removeObstacle from "../mutations/goals/removeObstacle.js";
import type * as mutations_goals_setAchieved from "../mutations/goals/setAchieved.js";
import type * as mutations_goals_setExamResult from "../mutations/goals/setExamResult.js";
import type * as mutations_goals_update from "../mutations/goals/update.js";
import type * as mutations_goals_updateObstacle from "../mutations/goals/updateObstacle.js";
import type * as mutations_items_applyOrder from "../mutations/items/applyOrder.js";
import type * as mutations_items_create from "../mutations/items/create.js";
import type * as mutations_items_remove from "../mutations/items/remove.js";
import type * as mutations_items_rename from "../mutations/items/rename.js";
import type * as mutations_methods_applyLaneOrder from "../mutations/methods/applyLaneOrder.js";
import type * as mutations_methods_applyMethodOrder from "../mutations/methods/applyMethodOrder.js";
import type * as mutations_methods_createLane from "../mutations/methods/createLane.js";
import type * as mutations_methods_createMethod from "../mutations/methods/createMethod.js";
import type * as mutations_methods_removeLane from "../mutations/methods/removeLane.js";
import type * as mutations_methods_removeMethod from "../mutations/methods/removeMethod.js";
import type * as mutations_methods_renameLane from "../mutations/methods/renameLane.js";
import type * as mutations_methods_setNowViewing from "../mutations/methods/setNowViewing.js";
import type * as mutations_methods_updateMethod from "../mutations/methods/updateMethod.js";
import type * as mutations_notifications_evaluate from "../mutations/notifications/evaluate.js";
import type * as mutations_notifications_markAllRead from "../mutations/notifications/markAllRead.js";
import type * as mutations_notifications_markRead from "../mutations/notifications/markRead.js";
import type * as mutations_notifications_pruneWebPushSubscriptions from "../mutations/notifications/pruneWebPushSubscriptions.js";
import type * as mutations_notifications_purgeExpired from "../mutations/notifications/purgeExpired.js";
import type * as mutations_notifications_saveSettings from "../mutations/notifications/saveSettings.js";
import type * as mutations_notifications_subscribePush from "../mutations/notifications/subscribePush.js";
import type * as mutations_notifications_unsubscribePush from "../mutations/notifications/unsubscribePush.js";
import type * as mutations_presets_create from "../mutations/presets/create.js";
import type * as mutations_presets_remove from "../mutations/presets/remove.js";
import type * as mutations_presets_saveSettings from "../mutations/presets/saveSettings.js";
import type * as mutations_presets_update from "../mutations/presets/update.js";
import type * as mutations_profile_claimAvatarUpload from "../mutations/profile/claimAvatarUpload.js";
import type * as mutations_profile_generateAvatarUploadUrl from "../mutations/profile/generateAvatarUploadUrl.js";
import type * as mutations_profile_purgeExpiredAvatarClaims from "../mutations/profile/purgeExpiredAvatarClaims.js";
import type * as mutations_rows_add from "../mutations/rows/add.js";
import type * as mutations_rows_applyOrder from "../mutations/rows/applyOrder.js";
import type * as mutations_rows_autoStopTimers from "../mutations/rows/autoStopTimers.js";
import type * as mutations_rows_confirm from "../mutations/rows/confirm.js";
import type * as mutations_rows_copyYesterdayConfirmed from "../mutations/rows/copyYesterdayConfirmed.js";
import type * as mutations_rows_pause from "../mutations/rows/pause.js";
import type * as mutations_rows_remove from "../mutations/rows/remove.js";
import type * as mutations_rows_reopen from "../mutations/rows/reopen.js";
import type * as mutations_rows_restore from "../mutations/rows/restore.js";
import type * as mutations_rows_resumeTimer from "../mutations/rows/resumeTimer.js";
import type * as mutations_rows_skip from "../mutations/rows/skip.js";
import type * as mutations_rows_start from "../mutations/rows/start.js";
import type * as mutations_rows_stopTimer from "../mutations/rows/stopTimer.js";
import type * as mutations_rows_switchPreset from "../mutations/rows/switchPreset.js";
import type * as mutations_rows_unconfirm from "../mutations/rows/unconfirm.js";
import type * as mutations_rows_unskip from "../mutations/rows/unskip.js";
import type * as mutations_targets_remove from "../mutations/targets/remove.js";
import type * as mutations_targets_save from "../mutations/targets/save.js";
import type * as mutations_trash_purgeDay from "../mutations/trash/purgeDay.js";
import type * as mutations_trash_purgeExpired from "../mutations/trash/purgeExpired.js";
import type * as mutations_trash_purgeRow from "../mutations/trash/purgeRow.js";
import type * as mutations_trash_removeDay from "../mutations/trash/removeDay.js";
import type * as mutations_trash_restoreDay from "../mutations/trash/restoreDay.js";
import type * as queries_auth_publicConfig from "../queries/auth/publicConfig.js";
import type * as queries_boardSchedule_listForWeek from "../queries/boardSchedule/listForWeek.js";
import type * as queries_categories_list from "../queries/categories/list.js";
import type * as queries_days_get from "../queries/days/get.js";
import type * as queries_goals_auditCheckpointParents from "../queries/goals/auditCheckpointParents.js";
import type * as queries_goals_list from "../queries/goals/list.js";
import type * as queries_goals_listObstacles from "../queries/goals/listObstacles.js";
import type * as queries_history_dayBreakdown from "../queries/history/dayBreakdown.js";
import type * as queries_history_month from "../queries/history/month.js";
import type * as queries_history_monthBreakdown from "../queries/history/monthBreakdown.js";
import type * as queries_history_presetReview from "../queries/history/presetReview.js";
import type * as queries_history_search from "../queries/history/search.js";
import type * as queries_history_week from "../queries/history/week.js";
import type * as queries_history_weekBreakdown from "../queries/history/weekBreakdown.js";
import type * as queries_history_yearHeatmap from "../queries/history/yearHeatmap.js";
import type * as queries_items_list from "../queries/items/list.js";
import type * as queries_items_recentConcreteActions from "../queries/items/recentConcreteActions.js";
import type * as queries_methods_list from "../queries/methods/list.js";
import type * as queries_notifications_list from "../queries/notifications/list.js";
import type * as queries_notifications_pushSubscriptions from "../queries/notifications/pushSubscriptions.js";
import type * as queries_notifications_settings from "../queries/notifications/settings.js";
import type * as queries_notifications_webPushConfig from "../queries/notifications/webPushConfig.js";
import type * as queries_notifications_webPushDelivery from "../queries/notifications/webPushDelivery.js";
import type * as queries_presets_list from "../queries/presets/list.js";
import type * as queries_presets_settings from "../queries/presets/settings.js";
import type * as queries_profile_getAvatarUrl from "../queries/profile/getAvatarUrl.js";
import type * as queries_review_monthlyReview from "../queries/review/monthlyReview.js";
import type * as queries_review_weeklyReview from "../queries/review/weeklyReview.js";
import type * as queries_rows_runningTimer from "../queries/rows/runningTimer.js";
import type * as queries_session_get from "../queries/session/get.js";
import type * as queries_setup_status from "../queries/setup/status.js";
import type * as queries_targets_listWithProgress from "../queries/targets/listWithProgress.js";
import type * as queries_trash_list from "../queries/trash/list.js";
import type * as services_boardSchedule_blocks from "../services/boardSchedule/blocks.js";
import type * as services_catalog_backfillItemSortOrders from "../services/catalog/backfillItemSortOrders.js";
import type * as services_catalog_ensure from "../services/catalog/ensure.js";
import type * as services_catalog_ensureCatalog from "../services/catalog/ensureCatalog.js";
import type * as services_categories_create from "../services/categories/create.js";
import type * as services_categories_list from "../services/categories/list.js";
import type * as services_categories_remove from "../services/categories/remove.js";
import type * as services_categories_rename from "../services/categories/rename.js";
import type * as services_days_collapseExtraLiveDays from "../services/days/collapseExtraLiveDays.js";
import type * as services_days_getDayByDate from "../services/days/getDayByDate.js";
import type * as services_days_getDayPage from "../services/days/getDayPage.js";
import type * as services_days_getLiveDay from "../services/days/getLiveDay.js";
import type * as services_days_liveRowsForDay from "../services/days/liveRowsForDay.js";
import type * as services_days_openDay from "../services/days/openDay.js";
import type * as services_days_requireEditableDay from "../services/days/requireEditableDay.js";
import type * as services_days_requireLiveDay from "../services/days/requireLiveDay.js";
import type * as services_days_setCondition from "../services/days/setCondition.js";
import type * as services_days_setMemo from "../services/days/setMemo.js";
import type * as services_days_toRowDtos from "../services/days/toRowDtos.js";
import type * as services_goals_applyMasteryProgressDelta from "../services/goals/applyMasteryProgressDelta.js";
import type * as services_goals_assertCheckpointParent from "../services/goals/assertCheckpointParent.js";
import type * as services_goals_assertGoalInput from "../services/goals/assertGoalInput.js";
import type * as services_goals_assertNoChildCheckpoints from "../services/goals/assertNoChildCheckpoints.js";
import type * as services_goals_assertScopeItems from "../services/goals/assertScopeItems.js";
import type * as services_goals_assertScopeUnfrozen from "../services/goals/assertScopeUnfrozen.js";
import type * as services_goals_auditCheckpointParents from "../services/goals/auditCheckpointParents.js";
import type * as services_goals_backfillCheckpointParents from "../services/goals/backfillCheckpointParents.js";
import type * as services_goals_countMasteryProgress from "../services/goals/countMasteryProgress.js";
import type * as services_goals_create from "../services/goals/create.js";
import type * as services_goals_createObstacle from "../services/goals/createObstacle.js";
import type * as services_goals_list from "../services/goals/list.js";
import type * as services_goals_listChildCheckpoints from "../services/goals/listChildCheckpoints.js";
import type * as services_goals_listObstacles from "../services/goals/listObstacles.js";
import type * as services_goals_loadDayItemTotals from "../services/goals/loadDayItemTotals.js";
import type * as services_goals_masteryDayTotals from "../services/goals/masteryDayTotals.js";
import type * as services_goals_masteryProgress from "../services/goals/masteryProgress.js";
import type * as services_goals_masteryProgressOf from "../services/goals/masteryProgressOf.js";
import type * as services_goals_planCheckpointParents from "../services/goals/planCheckpointParents.js";
import type * as services_goals_recomputeMasteryProgress from "../services/goals/recomputeMasteryProgress.js";
import type * as services_goals_recomputeMasteryProgressForOwner from "../services/goals/recomputeMasteryProgressForOwner.js";
import type * as services_goals_remove from "../services/goals/remove.js";
import type * as services_goals_removeObstacle from "../services/goals/removeObstacle.js";
import type * as services_goals_requireOwnedGoal from "../services/goals/requireOwnedGoal.js";
import type * as services_goals_scopeItemIds from "../services/goals/scopeItemIds.js";
import type * as services_goals_setAchieved from "../services/goals/setAchieved.js";
import type * as services_goals_setExamResult from "../services/goals/setExamResult.js";
import type * as services_goals_summarizeCheckpointParents from "../services/goals/summarizeCheckpointParents.js";
import type * as services_goals_toGoalDocument from "../services/goals/toGoalDocument.js";
import type * as services_goals_toGoalDto from "../services/goals/toGoalDto.js";
import type * as services_goals_update from "../services/goals/update.js";
import type * as services_goals_updateObstacle from "../services/goals/updateObstacle.js";
import type * as services_goals_validateGoalInput from "../services/goals/validateGoalInput.js";
import type * as services_goals_withMasteryProgressDelta from "../services/goals/withMasteryProgressDelta.js";
import type * as services_history_computeMonthBreakdown from "../services/history/computeMonthBreakdown.js";
import type * as services_history_computeWeekPage from "../services/history/computeWeekPage.js";
import type * as services_history_computeYearHeatmap from "../services/history/computeYearHeatmap.js";
import type * as services_history_dayBreakdown from "../services/history/dayBreakdown.js";
import type * as services_history_heatmapDays from "../services/history/heatmapDays.js";
import type * as services_history_liveRows from "../services/history/liveRows.js";
import type * as services_history_month from "../services/history/month.js";
import type * as services_history_monthBreakdown from "../services/history/monthBreakdown.js";
import type * as services_history_presetReview from "../services/history/presetReview.js";
import type * as services_history_rowToHistoryEvent from "../services/history/rowToHistoryEvent.js";
import type * as services_history_search from "../services/history/search.js";
import type * as services_history_shared from "../services/history/shared.js";
import type * as services_history_week from "../services/history/week.js";
import type * as services_history_weekBreakdown from "../services/history/weekBreakdown.js";
import type * as services_history_yearHeatmap from "../services/history/yearHeatmap.js";
import type * as services_items_applyOrder from "../services/items/applyOrder.js";
import type * as services_items_create from "../services/items/create.js";
import type * as services_items_helpers from "../services/items/helpers.js";
import type * as services_items_list from "../services/items/list.js";
import type * as services_items_recentConcreteActions from "../services/items/recentConcreteActions.js";
import type * as services_items_remove from "../services/items/remove.js";
import type * as services_items_rename from "../services/items/rename.js";
import type * as services_methods_applyLaneOrder from "../services/methods/applyLaneOrder.js";
import type * as services_methods_applyMethodOrder from "../services/methods/applyMethodOrder.js";
import type * as services_methods_createLane from "../services/methods/createLane.js";
import type * as services_methods_createMethod from "../services/methods/createMethod.js";
import type * as services_methods_helpers from "../services/methods/helpers.js";
import type * as services_methods_listCatalog from "../services/methods/listCatalog.js";
import type * as services_methods_removeLane from "../services/methods/removeLane.js";
import type * as services_methods_removeMethod from "../services/methods/removeMethod.js";
import type * as services_methods_renameLane from "../services/methods/renameLane.js";
import type * as services_methods_setNowViewing from "../services/methods/setNowViewing.js";
import type * as services_methods_updateMethod from "../services/methods/updateMethod.js";
import type * as services_notifications_emitNotification from "../services/notifications/emitNotification.js";
import type * as services_notifications_evaluate from "../services/notifications/evaluate.js";
import type * as services_notifications_evaluateCheckpointDeadline from "../services/notifications/evaluateCheckpointDeadline.js";
import type * as services_notifications_evaluateEveningUntouched from "../services/notifications/evaluateEveningUntouched.js";
import type * as services_notifications_evaluateWeeklyTargetMiss from "../services/notifications/evaluateWeeklyTargetMiss.js";
import type * as services_notifications_getOwnerSettings from "../services/notifications/getOwnerSettings.js";
import type * as services_notifications_list from "../services/notifications/list.js";
import type * as services_notifications_listPushSubscriptions from "../services/notifications/listPushSubscriptions.js";
import type * as services_notifications_loadDueSettings from "../services/notifications/loadDueSettings.js";
import type * as services_notifications_markAllRead from "../services/notifications/markAllRead.js";
import type * as services_notifications_markRead from "../services/notifications/markRead.js";
import type * as services_notifications_pruneWebPushSubscriptions from "../services/notifications/pruneWebPushSubscriptions.js";
import type * as services_notifications_purgeExpired from "../services/notifications/purgeExpired.js";
import type * as services_notifications_requireOwnedNotification from "../services/notifications/requireOwnedNotification.js";
import type * as services_notifications_saveSettings from "../services/notifications/saveSettings.js";
import type * as services_notifications_settings from "../services/notifications/settings.js";
import type * as services_notifications_subscribePush from "../services/notifications/subscribePush.js";
import type * as services_notifications_toNotificationDto from "../services/notifications/toNotificationDto.js";
import type * as services_notifications_unsubscribePush from "../services/notifications/unsubscribePush.js";
import type * as services_notifications_webPushConfig from "../services/notifications/webPushConfig.js";
import type * as services_notifications_webPushDelivery from "../services/notifications/webPushDelivery.js";
import type * as services_presets_create from "../services/presets/create.js";
import type * as services_presets_getSettings from "../services/presets/getSettings.js";
import type * as services_presets_helpers from "../services/presets/helpers.js";
import type * as services_presets_list from "../services/presets/list.js";
import type * as services_presets_remove from "../services/presets/remove.js";
import type * as services_presets_saveSettings from "../services/presets/saveSettings.js";
import type * as services_presets_update from "../services/presets/update.js";
import type * as services_profile_claimAvatarUpload from "../services/profile/claimAvatarUpload.js";
import type * as services_profile_getAvatarUrl from "../services/profile/getAvatarUrl.js";
import type * as services_profile_purgeExpiredAvatarClaims from "../services/profile/purgeExpiredAvatarClaims.js";
import type * as services_review_monthlyReview from "../services/review/monthlyReview.js";
import type * as services_review_weeklyReview from "../services/review/weeklyReview.js";
import type * as services_rows_add from "../services/rows/add.js";
import type * as services_rows_applyOrder from "../services/rows/applyOrder.js";
import type * as services_rows_autoStopTimers from "../services/rows/autoStopTimers.js";
import type * as services_rows_clearTimerFields from "../services/rows/clearTimerFields.js";
import type * as services_rows_confirm from "../services/rows/confirm.js";
import type * as services_rows_copyYesterdayConfirmed from "../services/rows/copyYesterdayConfirmed.js";
import type * as services_rows_findRunningTimerRow from "../services/rows/findRunningTimerRow.js";
import type * as services_rows_loadLiveRows from "../services/rows/loadLiveRows.js";
import type * as services_rows_loadRunningTimer from "../services/rows/loadRunningTimer.js";
import type * as services_rows_pause from "../services/rows/pause.js";
import type * as services_rows_remove from "../services/rows/remove.js";
import type * as services_rows_reopen from "../services/rows/reopen.js";
import type * as services_rows_requireOwnedRow from "../services/rows/requireOwnedRow.js";
import type * as services_rows_restore from "../services/rows/restore.js";
import type * as services_rows_resumeTimer from "../services/rows/resumeTimer.js";
import type * as services_rows_rowDayLiveness from "../services/rows/rowDayLiveness.js";
import type * as services_rows_skip from "../services/rows/skip.js";
import type * as services_rows_start from "../services/rows/start.js";
import type * as services_rows_stopRunningTimer from "../services/rows/stopRunningTimer.js";
import type * as services_rows_stopTimer from "../services/rows/stopTimer.js";
import type * as services_rows_switchPreset from "../services/rows/switchPreset.js";
import type * as services_rows_toRowTimerDto from "../services/rows/toRowTimerDto.js";
import type * as services_rows_unconfirm from "../services/rows/unconfirm.js";
import type * as services_rows_unskip from "../services/rows/unskip.js";
import type * as services_session_get from "../services/session/get.js";
import type * as services_setup_status from "../services/setup/status.js";
import type * as services_targets_aggregateByCategory from "../services/targets/aggregateByCategory.js";
import type * as services_targets_buildTargetProgress from "../services/targets/buildTargetProgress.js";
import type * as services_targets_listWithProgress from "../services/targets/listWithProgress.js";
import type * as services_targets_remove from "../services/targets/remove.js";
import type * as services_targets_save from "../services/targets/save.js";
import type * as services_trash_list from "../services/trash/list.js";
import type * as services_trash_purgeDay from "../services/trash/purgeDay.js";
import type * as services_trash_purgeExpired from "../services/trash/purgeExpired.js";
import type * as services_trash_purgeRow from "../services/trash/purgeRow.js";
import type * as services_trash_removeDay from "../services/trash/removeDay.js";
import type * as services_trash_restoreDay from "../services/trash/restoreDay.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  auth: typeof auth;
  crons: typeof crons;
  http: typeof http;
  "actions/notifications/deliverWebPush": typeof actions_notifications_deliverWebPush;
  "lib/achievementReflection": typeof lib_achievementReflection;
  "lib/authFields": typeof lib_authFields;
  "lib/avatarStorage": typeof lib_avatarStorage;
  "lib/boardScheduleColors": typeof lib_boardScheduleColors;
  "lib/boardScheduleRange": typeof lib_boardScheduleRange;
  "lib/catalog": typeof lib_catalog;
  "lib/catalogLoader": typeof lib_catalogLoader;
  "lib/categories": typeof lib_categories;
  "lib/categoryFields": typeof lib_categoryFields;
  "lib/completionRate": typeof lib_completionRate;
  "lib/concreteAction": typeof lib_concreteAction;
  "lib/concreteActionCore": typeof lib_concreteActionCore;
  "lib/conditions": typeof lib_conditions;
  "lib/dateArgs": typeof lib_dateArgs;
  "lib/dayView": typeof lib_dayView;
  "lib/domain": typeof lib_domain;
  "lib/env": typeof lib_env;
  "lib/errors": typeof lib_errors;
  "lib/examGoal": typeof lib_examGoal;
  "lib/historyBreakdown": typeof lib_historyBreakdown;
  "lib/holiday": typeof lib_holiday;
  "lib/holidayPreset": typeof lib_holidayPreset;
  "lib/itemOrder": typeof lib_itemOrder;
  "lib/itemSort": typeof lib_itemSort;
  "lib/jst": typeof lib_jst;
  "lib/methodOrder": typeof lib_methodOrder;
  "lib/monthlyReview": typeof lib_monthlyReview;
  "lib/movingAverage": typeof lib_movingAverage;
  "lib/notificationCopy": typeof lib_notificationCopy;
  "lib/notificationLink": typeof lib_notificationLink;
  "lib/notifications": typeof lib_notifications;
  "lib/owner": typeof lib_owner;
  "lib/ownerFunctions": typeof lib_ownerFunctions;
  "lib/preset": typeof lib_preset;
  "lib/presetDigest": typeof lib_presetDigest;
  "lib/rowTimer": typeof lib_rowTimer;
  "lib/scheduleInstant": typeof lib_scheduleInstant;
  "lib/searchText": typeof lib_searchText;
  "lib/setupStatus": typeof lib_setupStatus;
  "lib/share": typeof lib_share;
  "lib/toeicScore": typeof lib_toeicScore;
  "lib/trash": typeof lib_trash;
  "lib/validators": typeof lib_validators;
  "lib/volume": typeof lib_volume;
  "lib/webPush": typeof lib_webPush;
  "lib/weeklyReview": typeof lib_weeklyReview;
  migrations: typeof migrations;
  "mutations/boardSchedule/create": typeof mutations_boardSchedule_create;
  "mutations/boardSchedule/move": typeof mutations_boardSchedule_move;
  "mutations/boardSchedule/remove": typeof mutations_boardSchedule_remove;
  "mutations/boardSchedule/update": typeof mutations_boardSchedule_update;
  "mutations/catalog/ensure": typeof mutations_catalog_ensure;
  "mutations/categories/create": typeof mutations_categories_create;
  "mutations/categories/remove": typeof mutations_categories_remove;
  "mutations/categories/rename": typeof mutations_categories_rename;
  "mutations/days/open": typeof mutations_days_open;
  "mutations/days/setCondition": typeof mutations_days_setCondition;
  "mutations/days/setMemo": typeof mutations_days_setMemo;
  "mutations/goals/backfillCheckpointParents": typeof mutations_goals_backfillCheckpointParents;
  "mutations/goals/create": typeof mutations_goals_create;
  "mutations/goals/createObstacle": typeof mutations_goals_createObstacle;
  "mutations/goals/recomputeMasteryProgress": typeof mutations_goals_recomputeMasteryProgress;
  "mutations/goals/remove": typeof mutations_goals_remove;
  "mutations/goals/removeObstacle": typeof mutations_goals_removeObstacle;
  "mutations/goals/setAchieved": typeof mutations_goals_setAchieved;
  "mutations/goals/setExamResult": typeof mutations_goals_setExamResult;
  "mutations/goals/update": typeof mutations_goals_update;
  "mutations/goals/updateObstacle": typeof mutations_goals_updateObstacle;
  "mutations/items/applyOrder": typeof mutations_items_applyOrder;
  "mutations/items/create": typeof mutations_items_create;
  "mutations/items/remove": typeof mutations_items_remove;
  "mutations/items/rename": typeof mutations_items_rename;
  "mutations/methods/applyLaneOrder": typeof mutations_methods_applyLaneOrder;
  "mutations/methods/applyMethodOrder": typeof mutations_methods_applyMethodOrder;
  "mutations/methods/createLane": typeof mutations_methods_createLane;
  "mutations/methods/createMethod": typeof mutations_methods_createMethod;
  "mutations/methods/removeLane": typeof mutations_methods_removeLane;
  "mutations/methods/removeMethod": typeof mutations_methods_removeMethod;
  "mutations/methods/renameLane": typeof mutations_methods_renameLane;
  "mutations/methods/setNowViewing": typeof mutations_methods_setNowViewing;
  "mutations/methods/updateMethod": typeof mutations_methods_updateMethod;
  "mutations/notifications/evaluate": typeof mutations_notifications_evaluate;
  "mutations/notifications/markAllRead": typeof mutations_notifications_markAllRead;
  "mutations/notifications/markRead": typeof mutations_notifications_markRead;
  "mutations/notifications/pruneWebPushSubscriptions": typeof mutations_notifications_pruneWebPushSubscriptions;
  "mutations/notifications/purgeExpired": typeof mutations_notifications_purgeExpired;
  "mutations/notifications/saveSettings": typeof mutations_notifications_saveSettings;
  "mutations/notifications/subscribePush": typeof mutations_notifications_subscribePush;
  "mutations/notifications/unsubscribePush": typeof mutations_notifications_unsubscribePush;
  "mutations/presets/create": typeof mutations_presets_create;
  "mutations/presets/remove": typeof mutations_presets_remove;
  "mutations/presets/saveSettings": typeof mutations_presets_saveSettings;
  "mutations/presets/update": typeof mutations_presets_update;
  "mutations/profile/claimAvatarUpload": typeof mutations_profile_claimAvatarUpload;
  "mutations/profile/generateAvatarUploadUrl": typeof mutations_profile_generateAvatarUploadUrl;
  "mutations/profile/purgeExpiredAvatarClaims": typeof mutations_profile_purgeExpiredAvatarClaims;
  "mutations/rows/add": typeof mutations_rows_add;
  "mutations/rows/applyOrder": typeof mutations_rows_applyOrder;
  "mutations/rows/autoStopTimers": typeof mutations_rows_autoStopTimers;
  "mutations/rows/confirm": typeof mutations_rows_confirm;
  "mutations/rows/copyYesterdayConfirmed": typeof mutations_rows_copyYesterdayConfirmed;
  "mutations/rows/pause": typeof mutations_rows_pause;
  "mutations/rows/remove": typeof mutations_rows_remove;
  "mutations/rows/reopen": typeof mutations_rows_reopen;
  "mutations/rows/restore": typeof mutations_rows_restore;
  "mutations/rows/resumeTimer": typeof mutations_rows_resumeTimer;
  "mutations/rows/skip": typeof mutations_rows_skip;
  "mutations/rows/start": typeof mutations_rows_start;
  "mutations/rows/stopTimer": typeof mutations_rows_stopTimer;
  "mutations/rows/switchPreset": typeof mutations_rows_switchPreset;
  "mutations/rows/unconfirm": typeof mutations_rows_unconfirm;
  "mutations/rows/unskip": typeof mutations_rows_unskip;
  "mutations/targets/remove": typeof mutations_targets_remove;
  "mutations/targets/save": typeof mutations_targets_save;
  "mutations/trash/purgeDay": typeof mutations_trash_purgeDay;
  "mutations/trash/purgeExpired": typeof mutations_trash_purgeExpired;
  "mutations/trash/purgeRow": typeof mutations_trash_purgeRow;
  "mutations/trash/removeDay": typeof mutations_trash_removeDay;
  "mutations/trash/restoreDay": typeof mutations_trash_restoreDay;
  "queries/auth/publicConfig": typeof queries_auth_publicConfig;
  "queries/boardSchedule/listForWeek": typeof queries_boardSchedule_listForWeek;
  "queries/categories/list": typeof queries_categories_list;
  "queries/days/get": typeof queries_days_get;
  "queries/goals/auditCheckpointParents": typeof queries_goals_auditCheckpointParents;
  "queries/goals/list": typeof queries_goals_list;
  "queries/goals/listObstacles": typeof queries_goals_listObstacles;
  "queries/history/dayBreakdown": typeof queries_history_dayBreakdown;
  "queries/history/month": typeof queries_history_month;
  "queries/history/monthBreakdown": typeof queries_history_monthBreakdown;
  "queries/history/presetReview": typeof queries_history_presetReview;
  "queries/history/search": typeof queries_history_search;
  "queries/history/week": typeof queries_history_week;
  "queries/history/weekBreakdown": typeof queries_history_weekBreakdown;
  "queries/history/yearHeatmap": typeof queries_history_yearHeatmap;
  "queries/items/list": typeof queries_items_list;
  "queries/items/recentConcreteActions": typeof queries_items_recentConcreteActions;
  "queries/methods/list": typeof queries_methods_list;
  "queries/notifications/list": typeof queries_notifications_list;
  "queries/notifications/pushSubscriptions": typeof queries_notifications_pushSubscriptions;
  "queries/notifications/settings": typeof queries_notifications_settings;
  "queries/notifications/webPushConfig": typeof queries_notifications_webPushConfig;
  "queries/notifications/webPushDelivery": typeof queries_notifications_webPushDelivery;
  "queries/presets/list": typeof queries_presets_list;
  "queries/presets/settings": typeof queries_presets_settings;
  "queries/profile/getAvatarUrl": typeof queries_profile_getAvatarUrl;
  "queries/review/monthlyReview": typeof queries_review_monthlyReview;
  "queries/review/weeklyReview": typeof queries_review_weeklyReview;
  "queries/rows/runningTimer": typeof queries_rows_runningTimer;
  "queries/session/get": typeof queries_session_get;
  "queries/setup/status": typeof queries_setup_status;
  "queries/targets/listWithProgress": typeof queries_targets_listWithProgress;
  "queries/trash/list": typeof queries_trash_list;
  "services/boardSchedule/blocks": typeof services_boardSchedule_blocks;
  "services/catalog/backfillItemSortOrders": typeof services_catalog_backfillItemSortOrders;
  "services/catalog/ensure": typeof services_catalog_ensure;
  "services/catalog/ensureCatalog": typeof services_catalog_ensureCatalog;
  "services/categories/create": typeof services_categories_create;
  "services/categories/list": typeof services_categories_list;
  "services/categories/remove": typeof services_categories_remove;
  "services/categories/rename": typeof services_categories_rename;
  "services/days/collapseExtraLiveDays": typeof services_days_collapseExtraLiveDays;
  "services/days/getDayByDate": typeof services_days_getDayByDate;
  "services/days/getDayPage": typeof services_days_getDayPage;
  "services/days/getLiveDay": typeof services_days_getLiveDay;
  "services/days/liveRowsForDay": typeof services_days_liveRowsForDay;
  "services/days/openDay": typeof services_days_openDay;
  "services/days/requireEditableDay": typeof services_days_requireEditableDay;
  "services/days/requireLiveDay": typeof services_days_requireLiveDay;
  "services/days/setCondition": typeof services_days_setCondition;
  "services/days/setMemo": typeof services_days_setMemo;
  "services/days/toRowDtos": typeof services_days_toRowDtos;
  "services/goals/applyMasteryProgressDelta": typeof services_goals_applyMasteryProgressDelta;
  "services/goals/assertCheckpointParent": typeof services_goals_assertCheckpointParent;
  "services/goals/assertGoalInput": typeof services_goals_assertGoalInput;
  "services/goals/assertNoChildCheckpoints": typeof services_goals_assertNoChildCheckpoints;
  "services/goals/assertScopeItems": typeof services_goals_assertScopeItems;
  "services/goals/assertScopeUnfrozen": typeof services_goals_assertScopeUnfrozen;
  "services/goals/auditCheckpointParents": typeof services_goals_auditCheckpointParents;
  "services/goals/backfillCheckpointParents": typeof services_goals_backfillCheckpointParents;
  "services/goals/countMasteryProgress": typeof services_goals_countMasteryProgress;
  "services/goals/create": typeof services_goals_create;
  "services/goals/createObstacle": typeof services_goals_createObstacle;
  "services/goals/list": typeof services_goals_list;
  "services/goals/listChildCheckpoints": typeof services_goals_listChildCheckpoints;
  "services/goals/listObstacles": typeof services_goals_listObstacles;
  "services/goals/loadDayItemTotals": typeof services_goals_loadDayItemTotals;
  "services/goals/masteryDayTotals": typeof services_goals_masteryDayTotals;
  "services/goals/masteryProgress": typeof services_goals_masteryProgress;
  "services/goals/masteryProgressOf": typeof services_goals_masteryProgressOf;
  "services/goals/planCheckpointParents": typeof services_goals_planCheckpointParents;
  "services/goals/recomputeMasteryProgress": typeof services_goals_recomputeMasteryProgress;
  "services/goals/recomputeMasteryProgressForOwner": typeof services_goals_recomputeMasteryProgressForOwner;
  "services/goals/remove": typeof services_goals_remove;
  "services/goals/removeObstacle": typeof services_goals_removeObstacle;
  "services/goals/requireOwnedGoal": typeof services_goals_requireOwnedGoal;
  "services/goals/scopeItemIds": typeof services_goals_scopeItemIds;
  "services/goals/setAchieved": typeof services_goals_setAchieved;
  "services/goals/setExamResult": typeof services_goals_setExamResult;
  "services/goals/summarizeCheckpointParents": typeof services_goals_summarizeCheckpointParents;
  "services/goals/toGoalDocument": typeof services_goals_toGoalDocument;
  "services/goals/toGoalDto": typeof services_goals_toGoalDto;
  "services/goals/update": typeof services_goals_update;
  "services/goals/updateObstacle": typeof services_goals_updateObstacle;
  "services/goals/validateGoalInput": typeof services_goals_validateGoalInput;
  "services/goals/withMasteryProgressDelta": typeof services_goals_withMasteryProgressDelta;
  "services/history/computeMonthBreakdown": typeof services_history_computeMonthBreakdown;
  "services/history/computeWeekPage": typeof services_history_computeWeekPage;
  "services/history/computeYearHeatmap": typeof services_history_computeYearHeatmap;
  "services/history/dayBreakdown": typeof services_history_dayBreakdown;
  "services/history/heatmapDays": typeof services_history_heatmapDays;
  "services/history/liveRows": typeof services_history_liveRows;
  "services/history/month": typeof services_history_month;
  "services/history/monthBreakdown": typeof services_history_monthBreakdown;
  "services/history/presetReview": typeof services_history_presetReview;
  "services/history/rowToHistoryEvent": typeof services_history_rowToHistoryEvent;
  "services/history/search": typeof services_history_search;
  "services/history/shared": typeof services_history_shared;
  "services/history/week": typeof services_history_week;
  "services/history/weekBreakdown": typeof services_history_weekBreakdown;
  "services/history/yearHeatmap": typeof services_history_yearHeatmap;
  "services/items/applyOrder": typeof services_items_applyOrder;
  "services/items/create": typeof services_items_create;
  "services/items/helpers": typeof services_items_helpers;
  "services/items/list": typeof services_items_list;
  "services/items/recentConcreteActions": typeof services_items_recentConcreteActions;
  "services/items/remove": typeof services_items_remove;
  "services/items/rename": typeof services_items_rename;
  "services/methods/applyLaneOrder": typeof services_methods_applyLaneOrder;
  "services/methods/applyMethodOrder": typeof services_methods_applyMethodOrder;
  "services/methods/createLane": typeof services_methods_createLane;
  "services/methods/createMethod": typeof services_methods_createMethod;
  "services/methods/helpers": typeof services_methods_helpers;
  "services/methods/listCatalog": typeof services_methods_listCatalog;
  "services/methods/removeLane": typeof services_methods_removeLane;
  "services/methods/removeMethod": typeof services_methods_removeMethod;
  "services/methods/renameLane": typeof services_methods_renameLane;
  "services/methods/setNowViewing": typeof services_methods_setNowViewing;
  "services/methods/updateMethod": typeof services_methods_updateMethod;
  "services/notifications/emitNotification": typeof services_notifications_emitNotification;
  "services/notifications/evaluate": typeof services_notifications_evaluate;
  "services/notifications/evaluateCheckpointDeadline": typeof services_notifications_evaluateCheckpointDeadline;
  "services/notifications/evaluateEveningUntouched": typeof services_notifications_evaluateEveningUntouched;
  "services/notifications/evaluateWeeklyTargetMiss": typeof services_notifications_evaluateWeeklyTargetMiss;
  "services/notifications/getOwnerSettings": typeof services_notifications_getOwnerSettings;
  "services/notifications/list": typeof services_notifications_list;
  "services/notifications/listPushSubscriptions": typeof services_notifications_listPushSubscriptions;
  "services/notifications/loadDueSettings": typeof services_notifications_loadDueSettings;
  "services/notifications/markAllRead": typeof services_notifications_markAllRead;
  "services/notifications/markRead": typeof services_notifications_markRead;
  "services/notifications/pruneWebPushSubscriptions": typeof services_notifications_pruneWebPushSubscriptions;
  "services/notifications/purgeExpired": typeof services_notifications_purgeExpired;
  "services/notifications/requireOwnedNotification": typeof services_notifications_requireOwnedNotification;
  "services/notifications/saveSettings": typeof services_notifications_saveSettings;
  "services/notifications/settings": typeof services_notifications_settings;
  "services/notifications/subscribePush": typeof services_notifications_subscribePush;
  "services/notifications/toNotificationDto": typeof services_notifications_toNotificationDto;
  "services/notifications/unsubscribePush": typeof services_notifications_unsubscribePush;
  "services/notifications/webPushConfig": typeof services_notifications_webPushConfig;
  "services/notifications/webPushDelivery": typeof services_notifications_webPushDelivery;
  "services/presets/create": typeof services_presets_create;
  "services/presets/getSettings": typeof services_presets_getSettings;
  "services/presets/helpers": typeof services_presets_helpers;
  "services/presets/list": typeof services_presets_list;
  "services/presets/remove": typeof services_presets_remove;
  "services/presets/saveSettings": typeof services_presets_saveSettings;
  "services/presets/update": typeof services_presets_update;
  "services/profile/claimAvatarUpload": typeof services_profile_claimAvatarUpload;
  "services/profile/getAvatarUrl": typeof services_profile_getAvatarUrl;
  "services/profile/purgeExpiredAvatarClaims": typeof services_profile_purgeExpiredAvatarClaims;
  "services/review/monthlyReview": typeof services_review_monthlyReview;
  "services/review/weeklyReview": typeof services_review_weeklyReview;
  "services/rows/add": typeof services_rows_add;
  "services/rows/applyOrder": typeof services_rows_applyOrder;
  "services/rows/autoStopTimers": typeof services_rows_autoStopTimers;
  "services/rows/clearTimerFields": typeof services_rows_clearTimerFields;
  "services/rows/confirm": typeof services_rows_confirm;
  "services/rows/copyYesterdayConfirmed": typeof services_rows_copyYesterdayConfirmed;
  "services/rows/findRunningTimerRow": typeof services_rows_findRunningTimerRow;
  "services/rows/loadLiveRows": typeof services_rows_loadLiveRows;
  "services/rows/loadRunningTimer": typeof services_rows_loadRunningTimer;
  "services/rows/pause": typeof services_rows_pause;
  "services/rows/remove": typeof services_rows_remove;
  "services/rows/reopen": typeof services_rows_reopen;
  "services/rows/requireOwnedRow": typeof services_rows_requireOwnedRow;
  "services/rows/restore": typeof services_rows_restore;
  "services/rows/resumeTimer": typeof services_rows_resumeTimer;
  "services/rows/rowDayLiveness": typeof services_rows_rowDayLiveness;
  "services/rows/skip": typeof services_rows_skip;
  "services/rows/start": typeof services_rows_start;
  "services/rows/stopRunningTimer": typeof services_rows_stopRunningTimer;
  "services/rows/stopTimer": typeof services_rows_stopTimer;
  "services/rows/switchPreset": typeof services_rows_switchPreset;
  "services/rows/toRowTimerDto": typeof services_rows_toRowTimerDto;
  "services/rows/unconfirm": typeof services_rows_unconfirm;
  "services/rows/unskip": typeof services_rows_unskip;
  "services/session/get": typeof services_session_get;
  "services/setup/status": typeof services_setup_status;
  "services/targets/aggregateByCategory": typeof services_targets_aggregateByCategory;
  "services/targets/buildTargetProgress": typeof services_targets_buildTargetProgress;
  "services/targets/listWithProgress": typeof services_targets_listWithProgress;
  "services/targets/remove": typeof services_targets_remove;
  "services/targets/save": typeof services_targets_save;
  "services/trash/list": typeof services_trash_list;
  "services/trash/purgeDay": typeof services_trash_purgeDay;
  "services/trash/purgeExpired": typeof services_trash_purgeExpired;
  "services/trash/purgeRow": typeof services_trash_purgeRow;
  "services/trash/removeDay": typeof services_trash_removeDay;
  "services/trash/restoreDay": typeof services_trash_restoreDay;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {
  betterAuth: import("../betterAuth/_generated/component.js").ComponentApi<"betterAuth">;
  migrations: import("@convex-dev/migrations/_generated/component.js").ComponentApi<"migrations">;
};
