/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrashRouteImport } from './routes/trash'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as PresetsRouteImport } from './routes/presets'
import { Route as MyPageRouteImport } from './routes/my-page'
import { Route as ItemsRouteImport } from './routes/items'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as BoardRouteImport } from './routes/board'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MyPageIndexRouteImport } from './routes/my-page.index'
import { Route as MyPageStatusRouteImport } from './routes/my-page.status'
import { Route as MyPageNotificationsRouteImport } from './routes/my-page.notifications'
import { Route as DaysDateJstRouteImport } from './routes/days.$dateJst'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const TrashRoute = TrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const PresetsRoute = PresetsRouteImport.update({
  id: '/presets',
  path: '/presets',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPageRoute = MyPageRouteImport.update({
  id: '/my-page',
  path: '/my-page',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsRoute = ItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPageIndexRoute = MyPageIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MyPageRoute,
} as any)
const MyPageStatusRoute = MyPageStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => MyPageRoute,
} as any)
const MyPageNotificationsRoute = MyPageNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => MyPageRoute,
} as any)
const DaysDateJstRoute = DaysDateJstRouteImport.update({
  id: '/days/$dateJst',
  path: '/days/$dateJst',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/board': typeof BoardRoute
  '/goals': typeof GoalsRoute
  '/history': typeof HistoryRoute
  '/items': typeof ItemsRoute
  '/my-page': typeof MyPageRouteWithChildren
  '/presets': typeof PresetsRoute
  '/review': typeof ReviewRoute
  '/trash': typeof TrashRoute
  '/days/$dateJst': typeof DaysDateJstRoute
  '/my-page/notifications': typeof MyPageNotificationsRoute
  '/my-page/status': typeof MyPageStatusRoute
  '/my-page/': typeof MyPageIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/board': typeof BoardRoute
  '/goals': typeof GoalsRoute
  '/history': typeof HistoryRoute
  '/items': typeof ItemsRoute
  '/presets': typeof PresetsRoute
  '/review': typeof ReviewRoute
  '/trash': typeof TrashRoute
  '/days/$dateJst': typeof DaysDateJstRoute
  '/my-page/notifications': typeof MyPageNotificationsRoute
  '/my-page/status': typeof MyPageStatusRoute
  '/my-page': typeof MyPageIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/board': typeof BoardRoute
  '/goals': typeof GoalsRoute
  '/history': typeof HistoryRoute
  '/items': typeof ItemsRoute
  '/my-page': typeof MyPageRouteWithChildren
  '/presets': typeof PresetsRoute
  '/review': typeof ReviewRoute
  '/trash': typeof TrashRoute
  '/days/$dateJst': typeof DaysDateJstRoute
  '/my-page/notifications': typeof MyPageNotificationsRoute
  '/my-page/status': typeof MyPageStatusRoute
  '/my-page/': typeof MyPageIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/board'
    | '/goals'
    | '/history'
    | '/items'
    | '/my-page'
    | '/presets'
    | '/review'
    | '/trash'
    | '/days/$dateJst'
    | '/my-page/notifications'
    | '/my-page/status'
    | '/my-page/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/board'
    | '/goals'
    | '/history'
    | '/items'
    | '/presets'
    | '/review'
    | '/trash'
    | '/days/$dateJst'
    | '/my-page/notifications'
    | '/my-page/status'
    | '/my-page'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/board'
    | '/goals'
    | '/history'
    | '/items'
    | '/my-page'
    | '/presets'
    | '/review'
    | '/trash'
    | '/days/$dateJst'
    | '/my-page/notifications'
    | '/my-page/status'
    | '/my-page/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoardRoute: typeof BoardRoute
  GoalsRoute: typeof GoalsRoute
  HistoryRoute: typeof HistoryRoute
  ItemsRoute: typeof ItemsRoute
  MyPageRoute: typeof MyPageRouteWithChildren
  PresetsRoute: typeof PresetsRoute
  ReviewRoute: typeof ReviewRoute
  TrashRoute: typeof TrashRoute
  DaysDateJstRoute: typeof DaysDateJstRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trash': {
      id: '/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof TrashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presets': {
      id: '/presets'
      path: '/presets'
      fullPath: '/presets'
      preLoaderRoute: typeof PresetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-page': {
      id: '/my-page'
      path: '/my-page'
      fullPath: '/my-page'
      preLoaderRoute: typeof MyPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items': {
      id: '/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-page/': {
      id: '/my-page/'
      path: '/'
      fullPath: '/my-page/'
      preLoaderRoute: typeof MyPageIndexRouteImport
      parentRoute: typeof MyPageRoute
    }
    '/my-page/status': {
      id: '/my-page/status'
      path: '/status'
      fullPath: '/my-page/status'
      preLoaderRoute: typeof MyPageStatusRouteImport
      parentRoute: typeof MyPageRoute
    }
    '/my-page/notifications': {
      id: '/my-page/notifications'
      path: '/notifications'
      fullPath: '/my-page/notifications'
      preLoaderRoute: typeof MyPageNotificationsRouteImport
      parentRoute: typeof MyPageRoute
    }
    '/days/$dateJst': {
      id: '/days/$dateJst'
      path: '/days/$dateJst'
      fullPath: '/days/$dateJst'
      preLoaderRoute: typeof DaysDateJstRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MyPageRouteChildren {
  MyPageNotificationsRoute: typeof MyPageNotificationsRoute
  MyPageStatusRoute: typeof MyPageStatusRoute
  MyPageIndexRoute: typeof MyPageIndexRoute
}

const MyPageRouteChildren: MyPageRouteChildren = {
  MyPageNotificationsRoute: MyPageNotificationsRoute,
  MyPageStatusRoute: MyPageStatusRoute,
  MyPageIndexRoute: MyPageIndexRoute,
}

const MyPageRouteWithChildren =
  MyPageRoute._addFileChildren(MyPageRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoardRoute: BoardRoute,
  GoalsRoute: GoalsRoute,
  HistoryRoute: HistoryRoute,
  ItemsRoute: ItemsRoute,
  MyPageRoute: MyPageRouteWithChildren,
  PresetsRoute: PresetsRoute,
  ReviewRoute: ReviewRoute,
  TrashRoute: TrashRoute,
  DaysDateJstRoute: DaysDateJstRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
